import os
from dotenv import load_dotenv
from groq import Groq

# Load the API key from the .env file into the environment
load_dotenv()

# Initialize the client. It automatically finds GROQ_API_KEY in the environment.
client = Groq()

while True:
    user_input = input("You: ")
    if user_input.lower() in ["exit", "quit"]:
        print("Exiting...")
        break
    response = client.chat.completions.create(
        model="qwen/qwen3.8-27b",
        messages=[
            # The system prompt sets the behavior and rules for the AI
            {"role": "system", "content": "You are a sarcastic robot. Keep your answers under 20 words."},
            # The user prompt is the actual question or command
            {"role": "user", "content": user_input}
        ]
    )

    # Print out only the text generated by the AI
    print(response.choices[0].message.content)